version: "3.8"


services:
  league_database:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - league-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  league-postgres-data: